name:                neuropsicotesis
version:             0.1.0.0
github:              "githubuser/neuropsicotesis"
license:             GPL-3
author:              "David Villasana Jiménez"
maintainer:          "davidvillasana14@gmail.com"
copyright:           "2024 David Villasana Jiménez"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Web app for neuropsychological tests

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- persistent
- persistent-postgresql
- persistent-template
- monad-logger
- bytestring
- network
- warp
- wai
- wai-extra
- aeson
- mtl
- text
- cookie

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  neuropsicotesis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neuropsicotesis

tests:
  neuropsicotesis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neuropsicotesis
